"""Backward-compatible public API for the binary hardening pipeline."""

from binary_hardening.api import (
    FMTSTR_CHECKER_STEP,
    INITIALIZE_FRAMES_STEP,
    RNG_PATCHER_STEP,
    SHADOW_STACK_STEP,
    EntryInjectionResult,
    FrameInitializationResult,
    FmtStrCheckerStepOptions,
    FmtStrPatchResult,
    InitializeFramesStepOptions,
    InjectionResult,
    PipelineOptions,
    PipelineResult,
    RngPatchResult,
    RngPatcherStepOptions,
    ShadowStackStepOptions,
    SkippedFunction,
    initialize_stack_frames,
    inject_entry_trampolines,
    inject_trampolines,
    patch_format_strings,
    patch_rng_functions,
    run_hardening_pipeline,
    run_injection_pipeline,
)

__all__ = [
    "EntryInjectionResult",
    "FMTSTR_CHECKER_STEP",
    "INITIALIZE_FRAMES_STEP",
    "FrameInitializationResult",
    "FmtStrCheckerStepOptions",
    "FmtStrPatchResult",
    "InitializeFramesStepOptions",
    "InjectionResult",
    "PipelineOptions",
    "PipelineResult",
    "RNG_PATCHER_STEP",
    "RngPatchResult",
    "RngPatcherStepOptions",
    "SHADOW_STACK_STEP",
    "ShadowStackStepOptions",
    "SkippedFunction",
    "initialize_stack_frames",
    "inject_entry_trampolines",
    "inject_trampolines",
    "patch_format_strings",
    "patch_rng_functions",
    "run_hardening_pipeline",
    "run_injection_pipeline",
]
